### ISSUE TITLE
Incompatible with Django 1.8

### ISSUE THREAD

**Issue by wolfhechel** [twidi/django-templates-macros#2]
Private Template API has been moved to django.template.base as described in the [Release Notes](https://docs.djangoproject.com/en/1.8/releases/1.8/#cleanup-of-the-django-template-namespace)

Currently loading macros in a template raises Exception:

```
TemplateSyntaxError: 'macros' is not a valid tag library: ImportError raised loading macros.templatetags.macros: cannot import name FilterExpression
```

**Comment by twidi** [comment]
Fixed with version 0.2 Thanks for your PR
